//
//  GlobalValuesWorker.swift
//  MarketCoins
//
//  Created by Willian Peres on 22/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GlobalValuesWorker {
    private let dataProvider: GlobalValuesDataProvider?
    private var completion: ((Result<GlobalModel?, CryptocurrenciesError>) -> Void)?
    
    init(dataProvider: GlobalValuesDataProvider = GlobalValuesDataProvider()) {
        self.dataProvider = dataProvider
        self.dataProvider?.delegate = self
    }
    
    func doFetchGlobalValues(completion: @escaping ((Result<GlobalModel?, CryptocurrenciesError>) -> Void)) {
        dataProvider?.fetchGlobalValues()
        self.completion = completion
    }
}

extension GlobalValuesWorker: GlobalValuesDataProviderDelegate {
    func success(model: Any) {
        guard let completion = completion else {
            fatalError("GlobalValuesWorker: Completion not implemented")
        }
        
        completion(.success(model as? GlobalModel))
    }
    
    func errorData(_ provider: GenericDataProviderDelegate?, error: Error) {
        guard let completion = completion else {
            fatalError("GlobalValuesWorker: Completion not implemented")
        }
        
        switch error.errorCode {
        case 500:
            completion(.failure(.internalServerError))
        case 400:
            completion(.failure(.badRequestError))
        case 404:
            completion(.failure(.notFoundError))
        case 429:
            completion(.failure(.tooManyRequests))
        default:
            completion(.failure(.undefinedError))
        }
    }
}
